### PR TITLE
Weighted KDN Class, Tutorial, and Experiments

### PR DESCRIPTION
**Pull request by Laknath1996**
Hi, 

This PR includes the following:

1. The updated KDN class
2. Tutorial on global network linearity based weighting
3. G-XOR, Spiral, and GSP experiments
4. Results and plots from the above experiments

Thank you.

Best, 
Ashwin

### CODE REVIEW

**Review by PSSF23 — CHANGES_REQUESTED** [review]
@Laknath1996 

- Remove unnecessary symbols like `%%` and `black` format the files (including notebooks, use `black[jupyter]`).
- Make the spiral 2x3 figure text larger (currently hard to read)

**Review by PSSF23 — COMMENTED** [review]
The changes in #15 and yours on `kdn.py` will result in conflicts. Do you and @tiffanyformosa  have an agreement on how to proceed?

**Comment by tiffanyformosa** [comment]
My understanding from talking with Jayanta and Ashwin is that I need to push my changes ( #15 ) to a different branch besides kdg/main, but I am unsure if I can create the new branch myself or if it has to be created for me. I have also opened a new PR adding some 2D simulations to neurodata so we can test our algorithms in a wider variety of settings.

**Comment by Laknath1996** [comment]
Hey @PSSF23, I made the changes you requested (imported eras correctly, formatted according to black, removed unwanted symbols, and increase font title size). 😊

**Review by jdey4 — APPROVED** [review]

**Pull request merged**
