### PR TITLE
Add additional 2D simulations to KDG

### PR DESCRIPTION
**Pull request by tiffanyformosa**
Added the following simulations, derived from hyppo, to kdg.utils:
- Elllipse
- Sinewave (nπ)
- Stepped
- Polynomial (linear, quadratic, cubic, roots, etc)

### CODE REVIEW

**Review by PSSF23 — COMMENTED** [review]
Is there an issue associated with this PR?

**Comment by tiffanyformosa** [comment]
Hi Hao,

There isn't an issue associated with this PR, this is just something Jayanta mentioned I could do last week that would be useful for the paper. Should I open an issue? I'll run the notebook now.

**Comment by tiffanyformosa** [comment]
> And you need to run the notebook and show the figures

Ran the notebook. Results here: https://github.com/NeuroDataDesign/kdg/blob/2dsims/docs/tutorials/2dsimulations_example.ipynb

**Review by PSSF23 — APPROVED** [review]
LGTM

**Pull request merged**
