### PR TITLE
Weighted kdn tutorial

### PR DESCRIPTION
**Pull request by tiffanyformosa**
Adding Weighted KDN tutorial with helper functions.

### CODE REVIEW

**Review by PSSF23 — COMMENTED** [review]
@tiffanyformosa @Laknath1996 did you work on this issue together? I suggest Ashwin opening another issue about adding weighted tutorial.

**Review by PSSF23 — COMMENTED** [review]
If there are other issues involved in this PR point them out.

**Comment by Laknath1996** [comment]
> If there are other issues involved in this PR point them out.

Hey Hao, recently, I came up with a new weighting scheme (loosely based on the global linearity of an MLP -- I worked on this individually) which worked well with the spiral, G-XOR, and Gaussian Sparse Parity experiments. I showed the results and a rough sketch of this scheme, and I'm currently in the process of cleaning the code and writing down the math in a separate tutorial. Jayanta asked me that I PR this new KDN class once I'm done with the cleaning and documentation. Apart from that I'm hoping to compile some other experiments I did (KDCNN for instance) into a tutorial/ notebook and PR'ing them. Would that be okay?

**Comment by PSSF23** [comment]
@Laknath1996 Any plan you have with Jayanta works. I was trying to identify the contributors to this PR.

**Comment by Laknath1996** [comment]
> @Laknath1996 Any plan you have with Jayanta works. I was trying to identify the contributors to this PR.

Cool! As I mentioned before, I suppose did a decent contribution to the weighted_kdn branch especially regarding the scripts involving the kdn class, kdcnn class, and the scripts in the benchmark folder (plotting distance vs weights, kdcnn experiments with CIFAR-10 and MNIST, spiral experiment, adapting KDN to KDF, etc.). However, now that we have a newly minted KDN code that works decently, I was hoping to adapt the above scripts accordingly and make a PR to the neurodata/kdg. Would that be cool?

**Comment by PSSF23** [comment]
If @tiffanyformosa confirms that, we can wait for @jdey4 to decide how to incorporate your changes. @Laknath1996 by your words, it sounds like that the experiment code here is already outdated? If yes, I would suggest finishing the updates before merging this PR. You can use this PR directly.

On the code itself, you should remove the commented code/unnecessary symbols like "%%"

**Comment by Laknath1996** [comment]
> If @tiffanyformosa confirms that, we can wait for @jdey4 to decide how to incorporate your changes. @Laknath1996 by your words, it sounds like that the experiment code here is already outdated? If yes, I would suggest finishing the updates before merging this PR. You can use this PR directly.
> 
> On the code itself, you should remove the commented code/unnecessary symbols like "%%" and `black` format everything if not already (including notebooks).

Yup! there're some key changes in the new KDN code.. I'll clean and format the code as you have directed, and prepare to make the PR

**Review by PSSF23 — COMMENTED** [review]
@tiffanyformosa I moved your PR to a new base branch. @jdey4 will decide whether more changes are needed.

**Review by PSSF23 — CHANGES_REQUESTED** [review]
Your `keras` imports are mixed and thus wrong. You need to always use `tensorflow.keras` or the other way around.

**Comment by tiffanyformosa** [comment]
Fixed the keras imports; is there anything else I need to change?

**Review by PSSF23 — CHANGES_REQUESTED** [review]
@tiffanyformosa At least the first 3 files are still using the wrong `keras`.

**Comment by tiffanyformosa** [comment]
> @tiffanyformosa At least the first 3 files are still using the wrong `keras`.

Hi Hao, I checked all the listed changed files and they should be using the correct 'keras' now.

**Review by PSSF23 — COMMENTED** [review]
Cool. Now you can remove `keras` from the requirement list, and you need to `black` format your code.

**Comment by tiffanyformosa** [comment]
> Cool. Now you can remove `keras` from the requirement list, and you need to `black` format your code.
`keras` has been removed from the requirements list and all notebooks/benchmarks have been `black` formatted.

**Review by PSSF23 — CHANGES_REQUESTED** [review]
Ok. This should be the last thing: remove commented code & run the tutorial. All notebooks need to be fully run.

**Review by PSSF23 — APPROVED** [review]

**Pull request merged**
