### PR TITLE
Optimized KDN Class

### PR DESCRIPTION
**Pull request by Laknath1996**
This pull request contains an optimized version of the KDN class that follows from the ICML draft pseudocode.

### CODE REVIEW

**Review by PSSF23 — COMMENTED** [review]
I don't think the documentation should be removed. And the format could be optimized with `black`.

**Comment by Laknath1996** [comment]
I'll add the documentation back and format using black soon.

**Comment by Laknath1996** [comment]
Hey @PSSF23, I added the docstring and black-formatted the code.

**Review by PSSF23 — APPROVED** [review]
@Laknath1996 For confirmation, this is the code used in paper right?

**Comment by Laknath1996** [comment]
Hi @PSSF23, yeah, it follows the pseudocode we put in the draft. I verified the functionality of the code by testing on the spiral dataset

**Pull request merged**
